# _config.yaml
title: Kubism.io Helm Charts
description: A chart repo for all Kubism.IO Helm Charts.
theme: minima
url: "https://kubism.github.io/charts/"
repo_name: kubism.io

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
