{{ $fullname := include "dex.fullname" . }}
{{ $httpsTlsBuiltName := printf "%s-tls" $fullname }}
{{ $httpsTlsSecretName := default $httpsTlsBuiltName .Values.certs.web.secret.tlsName }}
{{ $grpcTlsServerBuiltName := printf "%s-server-tls" $fullname }}
{{ $grpcTlsServerSecretName := default $grpcTlsServerBuiltName .Values.certs.grpc.secret.serverTlsName }}
{{ $grpcCaBuiltName := printf "%s-ca" $fullname }}
{{ $grpcCaSecretName := default $grpcCaBuiltName .Values.certs.grpc.secret.caName }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dex.fullname" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "dex.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "dex.labels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "dex.serviceAccountName" . }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 10 }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: main
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
        - /usr/local/bin/dex
        - serve
        - /etc/dex/cfg/config.yaml
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - name: {{ if .Values.https }}https{{ else }}http{{ end }}
          containerPort: {{ .Values.ports.web.containerPort }}
          protocol: TCP
        {{- if .Values.grpc }}
        - name: grpc
          containerPort: {{ .Values.ports.grpc.containerPort }}
          protocol: TCP
        {{- end }}
        env:
{{ toYaml .Values.env | indent 10 }}
        volumeMounts:
        - mountPath: /etc/dex/cfg
          name: config
{{- if eq .Values.config.storage.type "postgres" }}
        - name: certs
          mountPath: /etc/dex
{{- end }}
{{- if .Values.https }}
        - mountPath: /etc/dex/tls/https/server
          name: https-tls
{{- end }}
{{- if and .Values.grpc .Values.certs.grpc.use }}
        - mountPath: /etc/dex/tls/grpc/server
          name: grpc-tls-server
        - mountPath: /etc/dex/tls/grpc/ca
          name: grpc-tls-ca
{{- end }}
{{- if ne (len .Values.extraVolumeMounts) 0 }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}
      volumes:
      - secret:
          defaultMode: 420
          items:
          - key: config.yaml
            path: config.yaml
          secretName: {{ if .Values.config.existingSecret }}{{ .Values.config.existingSecret }}{{ else }}{{ template "dex.fullname" . }}{{ end }}
        name: config
{{- if eq .Values.config.storage.type "postgres" }}
      - name: certs
        projected:
          sources:
            - secret:
                name: {{ .Values.config.storage.config.secret }}
                items:
                  - key: ca.crt
                    path: postgres.ca
                    mode: 0400
                  - key: tls.crt
                    path: client.crt
                    mode: 0400
                  - key: tls.key
                    path: client.key
                    mode: 0400
{{- end }}
{{- if .Values.https }}
      - name: https-tls
        secret:
          defaultMode: 420
          secretName: {{ $httpsTlsSecretName | quote }}
{{- end }}
{{- if and .Values.grpc .Values.certs.grpc.use }}
      - name: grpc-tls-server
        secret:
          defaultMode: 420
          secretName: {{ $grpcTlsServerSecretName | quote }}
      - name: grpc-tls-ca
        secret:
          defaultMode: 420
          secretName: {{ $grpcCaSecretName| quote }}
{{- end }}
{{- if ne (len .Values.extraVolumes) 0 }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
